version: 0.2

phases:
  install:
    runtime-version:
      java: correto8
  pre_build:
    commands:
      - echo Building jar actually a war
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/demo-1.0.war